name: Test Commits

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.3
      - name: Build
        run: go build -v ./...
      - name: Setup Local DynamoDB
        run: docker run -p 9000:8000 amazon/dynamodb-local &
      - name: Test
        run: go test -v ./... -count=1 -cover -race -vet=off
